-- Migration for table: project_wbs

-- UP
CREATE TABLE `project_wbs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `project_id` int(11) NOT NULL,
  `wbs_id` int(11) NOT NULL,
  `wbs_template_id` int(11) DEFAULT NULL,
  `project_type_id` int(11) DEFAULT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `display_order` int(11) NOT NULL DEFAULT 0,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `total_hours` decimal(10,2) DEFAULT 0.00,
  `note` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` tinyint(1) DEFAULT 1,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `deleted_by` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` datetime DEFAULT NULL,
  `budget_amount` decimal(15,2) DEFAULT 0.00,
  `actual_start_date` date DEFAULT NULL,
  `actual_end_date` date DEFAULT NULL,
  `actual_hours` decimal(10,2) DEFAULT 0.00,
  `planned_labour_cost` decimal(15,2) DEFAULT 0.00 COMMENT 'Planned employee cost for this WBS',
  `planned_material_cost` decimal(15,2) DEFAULT 0.00 COMMENT 'Planned material cost for this WBS',
  `planned_other_cost` decimal(15,2) DEFAULT 0.00 COMMENT 'Planned subcontract/other cost for this WBS',
  `quotation_discipline_id` int(11) DEFAULT NULL COMMENT 'FK to quotation_disciplines line that spawned this WBS row',
  `wbs_type` enum('labour','material','both') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'labour',
  `unit` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT 'hours',
  `planned_quantity` decimal(12,2) NOT NULL DEFAULT 0.00,
  `actual_quantity` decimal(12,2) DEFAULT 0.00,
  `rate` decimal(15,2) NOT NULL DEFAULT 0.00,
  `remaining_hours` decimal(10,2) DEFAULT 0.00,
  `extra_hours` decimal(10,2) DEFAULT 0.00,
  `progress_percent` decimal(5,2) DEFAULT 0.00,
  `level` int(11) DEFAULT 1,
  `wbs_code` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `wbs_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `baseline_start` date DEFAULT NULL,
  `baseline_end` date DEFAULT NULL,
  `current_start` date DEFAULT NULL,
  `current_end` date DEFAULT NULL,
  `baseline_duration` int(11) DEFAULT 0,
  `current_duration` int(11) DEFAULT 0,
  `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scope` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quality_standard` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `acceptance_criteria` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_project_id` (`project_id`),
  KEY `idx_wbs_id` (`wbs_id`),
  CONSTRAINT `fk_pwbs_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`project_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_pwbs_wbs` FOREIGN KEY (`wbs_id`) REFERENCES `work_breakdown_structures` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- DOWN
DROP TABLE IF EXISTS `project_wbs`;
