-- Migration for table: tasks

-- UP
CREATE TABLE `tasks` (
  `task_id` int(11) NOT NULL AUTO_INCREMENT,
  `project_id` int(11) NOT NULL,
  `quotation_id` int(11) DEFAULT NULL,
  `discipline_id` int(11) DEFAULT NULL,
  `wbs_id` int(11) DEFAULT NULL,
  `task_code` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `task_name` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `required_worker_count` int(11) NOT NULL DEFAULT 1,
  `estimated_hours` decimal(10,2) NOT NULL DEFAULT 0.00,
  `start_date` date DEFAULT NULL,
  `start_time` time DEFAULT NULL,
  `target_date` date DEFAULT NULL,
  `target_time` time DEFAULT NULL,
  `status` enum('pending','in_progress','in-progress','completed','delayed') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime DEFAULT NULL,
  `task_address` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `latitude` decimal(10,8) DEFAULT NULL,
  `longitude` decimal(11,8) DEFAULT NULL,
  `budget_amount` decimal(15,2) DEFAULT 0.00,
  `actual_start_date` date DEFAULT NULL,
  `actual_end_date` date DEFAULT NULL,
  `actual_cost` decimal(15,2) DEFAULT 0.00,
  `progress_percentage` int(11) DEFAULT 0,
  `priority` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'medium',
  `planned_labour_cost` decimal(15,2) DEFAULT 0.00,
  `planned_material_cost` decimal(15,2) DEFAULT 0.00,
  `planned_other_cost` decimal(15,2) DEFAULT 0.00,
  `wbs_template_id` int(11) DEFAULT NULL,
  `is_billable` tinyint(1) DEFAULT 1,
  `baseline_start` date DEFAULT NULL,
  `baseline_end` date DEFAULT NULL,
  `current_start` date DEFAULT NULL,
  `current_end` date DEFAULT NULL,
  `baseline_duration` int(11) DEFAULT 0,
  `current_duration` int(11) DEFAULT 0,
  `manually_adjusted` tinyint(1) DEFAULT 0,
  `planning_task_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`task_id`),
  KEY `idx_tasks_project` (`project_id`),
  KEY `fk_tasks_pwbs` (`wbs_id`),
  KEY `idx_tasks_pw` (`project_id`,`wbs_id`),
  CONSTRAINT `fk_tasks_projects` FOREIGN KEY (`project_id`) REFERENCES `projects` (`project_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_tasks_pwbs` FOREIGN KEY (`wbs_id`) REFERENCES `project_wbs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- DOWN
DROP TABLE IF EXISTS `tasks`;
